version: "3.9"

services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    volumes:
      - ./database:/directus/database      # ← SQLite visível no host
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    env_file: .env                         # segredos fora do YAML
    environment:
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "https://localhost"     # ajuste conforme domínio real

  frontend:
    build:
      context: ./amover-frontend
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - directus
    volumes:
      - ./certs/self.crt:/etc/ssl/certs/self.crt:ro
      - ./certs/self.key:/etc/ssl/private/self.key:ro

volumes: {}  # já não define nada, pois tudo é bind‑mount
