name: CI - Testes e Qualidade

on:
  pull_request:
    branches:
      - testes

jobs:
  build:
    name: Validar Código e Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Testes .NET
      - name: Testar .NET
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test
        working-directory: ./CSharpProject

      # Testes C e C++
      - name: Compilar e Testar C/C++
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./testExecutable
        working-directory: ./CppProject

      # Testes Python
      - name: Testar Python
        run: |
          pip install -r requirements.txt
          pytest
        working-directory: ./PythonProject

      # Testes Node.js
      - name: Testar Node.js
        run: |
          npm install
          npm test
        working-directory: ./NodeProject

      # Validação HTML/CSS
      - name: Validar HTML e CSS
        run: |
          npm install -g html-validator-cli
          html-validator --file index.html --verbose
          npm install -g stylelint
          stylelint "**/*.css"
        working-directory: ./HTMLCSSProject

      # Análise SonarQube
      - name: Análise SonarQube
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
