// src/constants/tags.js
export const TAGS = [
    'sustentabilidade',
    'mobilidade',
    'energia',
    'inovação',
    'digitalização',
    'investigação',
    'notícia',
    'relatório',
    'estudo',
    'tutorial',
    'evento',
    'anúncio',
    'interno',
    'público',
    'confidencial',
    'rascunho',
    'bolseiros',
    'técnicos',
    'orientadores',
    'admin',
    'software',
    'hardware',
    'infraestruturas',
    'processos',
    'logística',
    'engenharia',
    'biologia',
    'ciências sociais',
    'economia',
    'texto',
    'vídeo',
    'apresentação',
    'infográfico',
    'podcast'
  ];
  