name: Notify on Feature Push

on:
  push:
    branches:
      - feature/**  # Aciona o workflow apenas para branches que começam com "feature/"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Notification
      uses: actions/github-script@v6
      with:
        script: |
          const branchName = context.ref.replace('refs/heads/', '');
          const message = `
          🚀 **Push Detetado** na branch: \`${branchName}\` 🎉  
          Lembre-se de abrir um Pull Request quando terminar, para a brach testes 😊
          `;
          const issue = await github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Novo Push na Branch ${branchName}`,
            body: message,
          });
